version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://testuser:testpass@db:5432/testdb
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMA: public
      PGRST_JWT_SECRET: "disable"
    depends_on:
      - db